### ISSUE TITLE
Many questions I collected

### ISSUE THREAD

**Issue by andogy** [zhuaidadaya/MCH#3]
***THIS ISSUE WILL NOT BE CLOSED***

27/8/2021 13:04
1. English is not complete
2. UPD Check will not stop
3. java.io.FileNotFoundException
4.      at project.Community.Events.UPD.githubConnect.writeHosts(githubConnect.java:29)
        at project.Community.Events.UPD.URLs.UPD(URLs.java:72)
        at project.Community.Events.UPD.URLs.checkUPD(URLs.java:31)
        at project.Community.Events.UPD.URLs.run(URLs.java:311)
5. Debug log is garbled
6. The grammar of Traditional Chinese is wrong
7. In about page, delete **"翅膀(Chibang)"** and change to **"CB"***(Including other languages)*

27/8/2021 13:32
8. In Chinese*(And other)* mardown, I found some problems, like **"目前还没有发布第一个正式版本"**

27/8/2021 16:57
9. More note in code plz

**Comment by andogy** [comment]
give it up
